version: '3.8'
services:
  app:
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/bus/usb:/dev/bus/usb"
      - /dev/dxg:/dev/dxg                   # WSL GPU device

    cap_add:
      - SYS_NICE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    build: 
      context: .
      args:
        LIBFRANKA_VERSION: 0.8.0 # specify tag or commit hash if needed
        INSTALL_CUDA: "false" # set to "true" to install CUDA PyTorch 
    volumes:
      - ./:/app
      - /tmp:/tmp
      - /dev:/dev
      - /var/run:/var/run
      - /sys:/sys:rw
      - /mnt/ssd_data/diffusion_policy:/mnt/diffusion_policy

      - /tmp/.X11-unix:/tmp/.X11-unix       # X11 server
      - /mnt/wslg:/mnt/wslg                 # WSLg mount
      - /usr/lib/wsl:/usr/lib/wsl           # WSL GPU libraries
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      - QT_X11_NO_MITSHM=1
      
      # **Official Microsoft WSLg GPU environment variables**
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # 'graphics' and 'display' are crucial for MuJoCo rendering
              capabilities: [gpu, graphics, video, display, utility, compute]
    working_dir: /app
    tty: true
    command: /bin/bash
